app:
  dataSource:
    postgres:
      port: 5432
      username: fox
      password: foxminded
      host: localhost
      databaseName: school
      jdbc-url: jdbc:postgresql://${app.dataSource.postgres.host}:${app.dataSource.postgres.port}/${app.dataSource.postgres.databaseName}